[package]
name = "hwl"
authors = [ "Husayn al-Qurashi <husayn@dnmx.org>" ]
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
